Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Models/ErrorViewModel.cs
using System;

namespace Sol_Call_Action_Javascript.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace Sol_Call_Action_Javascript.Models
{
    [DataContract]
    public class UserModel
    {
        [DataMember(EmitDefaultValue =false)]
        public String firstName { get; set; }

        [DataMember(EmitDefaultValue =false)]
        public String lastName { get; set; }
    }
}

Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sol_Call_Action_Javascript.Models;

namespace Sol_Call_Action_Javascript.Controllers
{
    public class DemoController : Controller
    {

        public DemoController()
        {
            Users = new UserModel();
        }


        [BindProperty]
        public UserModel Users { get; set; }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult OnGetJson()
        {
            Users.firstName = "Kishor";
            Users.lastName = "Naik";

            return base.Json(Users);
        }

        [HttpPost]
        public IActionResult OnPostJson([FromBody]UserModel userModel)
        {
            return base.Json(userModel);
        }
    }
}

Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sol_Call_Action_Javascript.Models;

namespace Sol_Call_Action_Javascript.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Views/Demo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <button id="btnGetJson" class="btn btn-primary" onclick="onGetJsonSubmit(); return false;">Get Json</button>

                <div>
                    <h2 id="lblFirstName"></h2>
                    <h2 id="lblLastName"></h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <button id="btnPostGetJson" class="btn btn-primary" onclick="onPostGetJsonSubmit(); return false;">Get Post Json</button>
            </div>
        </div>
    </div>
</form>


@section Scripts {

<script type="text/javascript">

    function userModel() {
        this.firstName = undefined;
        this.lastName = undefined;
    }

    function onGetJsonSubmit() {

       $.ajax({
                type: "POST",
                url: '@Url.Action("OnGetJson","Demo")',
                contentType: "application/json",
                dataType: "json",
                success: function (response) {

                    console.log(response); // Response As Object

                    var userModelJson = JSON.stringify(response); // Convert Object to Json
                    console.log(userModelJson);

                    var userModelData = JSON.parse(userModelJson); // Convert Json into Object
                    console.log(userModelData);

                    // Map User Model Object
                    var userModelObj = new userModel();
                    userModelObj.firstName = userModelData.firstName;
                    userModelObj.lastName = userModelData.lastName;

                    // Print
                    $("div #lblFirstName").html(userModelObj.firstName);
                    $("div #lblLastName").html(userModelObj.lastName);
                    

                },
                failure: function (response) {
                    alert(response);
                }
            });
    }

    function onPostGetJsonSubmit() {

        var userModelObj = new userModel();
        userModelObj.firstName = "Yogesh";
        userModelObj.lastName = "Naik";

       

        $.ajax(
            {
                type: "POST",
                url: '@Url.Action("OnPostJson","Demo")',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(userModelObj),
                success: function (response) {

                     console.log(response); // Response As Object

                    var userModelJson = JSON.stringify(response); // Convert Object to Json
                    console.log(userModelJson);

                    var userModelData = JSON.parse(userModelJson); // Convert Json into Object
                    console.log(userModelData);

                    // Map User Model Object
                    var userModelObj = new userModel();
                    userModelObj.firstName = userModelData.firstName;
                    userModelObj.lastName = userModelData.lastName;

                    // Print
                    $("div #lblFirstName").html(userModelObj.firstName);
                    $("div #lblLastName").html(userModelObj.lastName);

                },
                failure: function (response) {
                    console.log(response);
                }
                
            });

    }

</script>

}

Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sol_Call_Action_Javascript/Sol_Call_Action_Javascript/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sol_Call_Action_Javascript</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sol_Call_Action_Javascript</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Sol_Call_Action_Javascript - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>